### ISSUE TITLE
cmake fails to build the Python binding: Could not find ... a package configuration file provided by "NumPy"

### ISSUE THREAD

**Issue by yurivict** [fastscape-lem/fastscapelib#111]
```
  Could not find a package configuration file provided by "NumPy" with any of
  the following names:

    NumPyConfig.cmake
    numpy-config.cmake

```

numpy doesn't install cmake files.

Python-3.9
py39-numpy-1.23.5_1,1
FreeBSD 13.1

**Comment by benbovy** [comment]
Hmm that's weird, CMake should use the `cmake/FindNumPy.cmake` module (added to the module path). How did you try to install the Python bindings?

(note: I plan to refactor soon the cmake configuration and use CMake's default modules to find Python/Numpy, or reuse scikit-build so that we don't have to care about that).

**Comment by yurivict** [comment]
I am not sure what happened before. It works now.

Thank you for your help.
