### ISSUE TITLE
Container vs view for grid neighbor indices

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscapelib#71]
> From https://github.com/fastscape-lem/fastscapelib/pull/70#discussion_r561139090: Maybe we could think to something similar for indices method.

Something like 

```cpp
for(auto neighbor_idx : grid.neighbors_indices(node_idx))
{
    // do something
}
```

is a very common use case where we just need to iterate once over grid node neighbors.

Doing something like [here](https://github.com/fastscape-lem/fastscapelib/blob/b19a051fc02a1e19105288f7ba766ec44aad0840/include/fastscapelib/flow_routing.hpp#L315) or even something similar with `neighbors_indices` seems a bit overkill to me. In fact, I don't see (yet?) much use cases where we would need a xtensor container when only dealing with the indices. I might be missing something, though.

I'm wondering if the return type of `structured_grid<G, C>::neighbors_indices(const size_type& idx)` (i.e., `neighbors_indice_type`) could be simply a custom range-like structure with `const_iterator` or a `const xt::view`, instead of a xtensor  container?

**Comment by adriendelsalle** [comment]
Hi @benbovy !

It was designed that way because when getting the `neighbors`, you either have returned or filled an `xtensor` container depending on the number of neighbors that is variable (`grid` type but also periodicity).
Having a similar behavior for `neighbors_indices` looks more natural.

You can't return a `const_iterator` or a `const xt::view` because you are not guaranteed that the data is cached/stored somewhere. It's also the reason why the methods that are returning are returning by value and not by reference.

Still, you can use:

```cpp
for(auto neighbor_idx : grid.neighbors_indices(node_idx))
{
    // do something
}
```
or
```cpp
for(auto neighbor : grid.neighbors(node_idx))
{
    // do something
}
```
but it may be less efficient than creating/allocating once then filling the data reusing the same container.

**Comment by adriendelsalle** [comment]
#75 allows the following syntax:
```cpp
neighbors_type neighbors;
neighbors_indices_type neighbors_indices;

for (auto i : grid.nodes_indices())
{
    for (auto n : grid.neighbors(i, neighbors))
    {          
        // do something
    }
   
    for (auto n : grid.neighbors_indices(i, neighbors_indices))
    {          
        // do something
    }
}
```

**Comment by benbovy** [comment]
> https://github.com/fastscape-lem/fastscapelib/pull/77 allows the following syntax

And that is working great! Thanks @adriendelsalle

(with some huge delay! As you can see I'm working back on the development of this library, hopefully a release soon with mention of the work that you've done here).
